import hashlib
import re
from .models import Chunk
from .scope import project_label
from .transcripts import (
    TranscriptEvent,
    extract_codex_file,
    extractor_version,
    iter_transcript_events,
)

# Bump when extraction logic changes -> baked into the per-file index signature so
# stale files are re-extracted on the next index run. v2 = harness-boilerplate filter.
EXTRACTOR_VERSION = 2
# Codex has an independent extraction contract.  Keeping a separate tag means
# adding/changing Codex support never invalidates (and re-embeds) an unchanged
# Claude corpus.

# Claude Code injects machine text into user turns (notifications, reminders, slash-command
# echoes, local-command output). It is NOT the user speaking, so it must not be embedded as
# conversational surface. We strip COMPLETE matched <tag>...</tag> blocks only: a user who
# merely quotes "<system-reminder>" mid-prose (no closing tag) is left untouched.
# WHY: docs/decisions/2026-06-25-extract-noise-and-dedup.md
_HARNESS_TAGS = (
    "system-reminder", "task-notification", "command-message", "command-name",
    "command-args", "local-command-stdout", "local-command-stderr",
)
_HARNESS_BLOCK = re.compile("|".join(rf"<{t}>.*?</{t}>" for t in _HARNESS_TAGS), re.DOTALL)
# Anchored on the full harness sentence / marker (not a bare "Caveat:") -> ~0 false positives.
_HARNESS_LINE = re.compile(
    r"(?m)^[ \t]*(?:Caveat: The messages below were generated by the user.*"
    r"|\[Request interrupted[^\]]*\])[ \t]*$"
)


def _clean_user_text(content: str) -> str | None:
    """Strip harness-injected boilerplate from a user turn.

    Returns the real residual text, or None if nothing substantive remains (a
    turn that was pure boilerplate). Matched tag PAIRS only — quoting an unclosed
    tag survives. The caller keeps byte_offset/byte_len on the raw line so
    expand_around still resolves to the original transcript.
    """
    cleaned = _HARNESS_BLOCK.sub("", content)
    cleaned = _HARNESS_LINE.sub("", cleaned)
    cleaned = cleaned.strip()
    return cleaned or None

def extractor_tag(source: str) -> str:
    version = extractor_version(source)
    return f"v{version}" if source == "claude" else f"codex-v{version}"


def _mk(event: TranscriptEvent, project: str, role: str, text: str) -> Chunk:
    return Chunk(
        session_id=event.session_id,
        uuid=event.uuid,
        role=role,
        text=text,
        project=project_label(event.cwd) or project,
        cwd=event.cwd,
        git_branch=event.git_branch,
        ts=event.ts,
        file_path="",  # filled by extract_file
        byte_offset=event.byte_offset,
        byte_len=event.byte_len,
        turn_index=event.turn_index,
        content_hash=hashlib.sha256(text.encode("utf-8")).hexdigest(),
        source=event.source,
    )


def _extract_claude(path: str, project: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    for event in iter_transcript_events(path, source="claude"):
        obj = event.obj
        msg = obj.get("message") or {}
        if obj.get("type") == "user" and isinstance(msg.get("content"), str):
            text = _clean_user_text(msg["content"])
            if text is None:
                continue  # pure harness boilerplate — not the user speaking
            chunk = _mk(event, project, "user", text)
            chunk.file_path = path
            chunks.append(chunk)
        elif obj.get("type") == "assistant" and isinstance(msg.get("content"), list):
            for block in msg["content"]:
                if isinstance(block, dict) and block.get("type") == "text":
                    text = block.get("text", "")
                    if not text.strip():
                        continue
                    chunk = _mk(event, project, "assistant", text)
                    chunk.file_path = path
                    chunks.append(chunk)
    return chunks


def _extract_codex(path: str, project: str) -> list[Chunk]:
    """Extract one copy of the visible Codex conversation surface.

    event_msg is the canonical clean surface. response_item messages, reasoning,
    and tools remain reachable through grep/expand but are never embedded.
    """
    return extract_codex_file(path, project=project)


def extract_file(path: str, project: str, source: str = "claude") -> list[Chunk]:
    if source == "claude":
        return _extract_claude(path, project)
    if source == "codex":
        return _extract_codex(path, project)
    raise ValueError(f"unknown transcript source: {source!r}")
