import hashlib
import json
import re
from datetime import datetime
from .models import Chunk
from .scope import project_label

# Bump when extraction logic changes -> baked into the per-file index signature so
# stale files are re-extracted on the next index run. v2 = harness-boilerplate filter.
EXTRACTOR_VERSION = 2

# Claude Code injects machine text into user turns (notifications, reminders, slash-command
# echoes, local-command output). It is NOT the user speaking, so it must not be embedded as
# conversational surface. We strip COMPLETE matched <tag>...</tag> blocks only: a user who
# merely quotes "<system-reminder>" mid-prose (no closing tag) is left untouched.
# WHY: docs/decisions/2026-06-25-extract-noise-and-dedup.md
_HARNESS_TAGS = (
    "system-reminder", "task-notification", "command-message", "command-name",
    "command-args", "local-command-stdout", "local-command-stderr",
)
_HARNESS_BLOCK = re.compile("|".join(rf"<{t}>.*?</{t}>" for t in _HARNESS_TAGS), re.DOTALL)
# Anchored on the full harness sentence / marker (not a bare "Caveat:") -> ~0 false positives.
_HARNESS_LINE = re.compile(
    r"(?m)^[ \t]*(?:Caveat: The messages below were generated by the user.*"
    r"|\[Request interrupted[^\]]*\])[ \t]*$"
)


def _clean_user_text(content: str) -> str | None:
    """Strip harness-injected boilerplate from a user turn.

    Returns the real residual text, or None if nothing substantive remains (a
    turn that was pure boilerplate). Matched tag PAIRS only — quoting an unclosed
    tag survives. The caller keeps byte_offset/byte_len on the raw line so
    expand_around still resolves to the original transcript.
    """
    cleaned = _HARNESS_BLOCK.sub("", content)
    cleaned = _HARNESS_LINE.sub("", cleaned)
    cleaned = cleaned.strip()
    return cleaned or None

def _ts(obj) -> int:
    s = obj.get("timestamp")
    if not s:
        return 0
    try:
        return int(datetime.fromisoformat(s.replace("Z", "+00:00")).timestamp())
    except ValueError:
        return 0

def _mk(obj, project, role, text, offset, length, turn_index) -> Chunk:
    cwd = obj.get("cwd", "")
    return Chunk(
        session_id=obj.get("sessionId", ""),
        uuid=obj.get("uuid", ""),
        role=role,
        text=text,
        project=project_label(cwd) or project,
        cwd=cwd,
        git_branch=obj.get("gitBranch", ""),
        ts=_ts(obj),
        file_path="",  # filled by caller-aware path below
        byte_offset=offset,
        byte_len=length,
        turn_index=turn_index,
        content_hash=hashlib.sha256(text.encode("utf-8")).hexdigest(),
    )

def extract_file(path: str, project: str) -> list[Chunk]:
    chunks: list[Chunk] = []
    offset = 0
    with open(path, "rb") as f:
        for turn_index, raw in enumerate(f):
            length = len(raw)
            line_offset = offset
            offset += length
            try:
                obj = json.loads(raw)
            except json.JSONDecodeError:
                continue
            t = obj.get("type")
            msg = obj.get("message") or {}
            if t == "user" and isinstance(msg.get("content"), str):
                text = _clean_user_text(msg["content"])
                if text is None:
                    continue  # pure harness boilerplate — not the user speaking
                c = _mk(obj, project, "user", text, line_offset, length, turn_index)
                c.file_path = path
                chunks.append(c)
            elif t == "assistant" and isinstance(msg.get("content"), list):
                for block in msg["content"]:
                    if isinstance(block, dict) and block.get("type") == "text":
                        text = block.get("text", "")
                        if not text.strip():
                            continue
                        c = _mk(obj, project, "assistant", text, line_offset, length, turn_index)
                        c.file_path = path
                        chunks.append(c)
    return chunks
