import json
import pathlib

from session_recall.extract import extract_file

FIX = str(pathlib.Path(__file__).parent / "fixtures" / "session_a.jsonl")

def test_extracts_only_surface():
    chunks = extract_file(FIX, project="proj")
    texts = [(c.role, c.text) for c in chunks]
    assert ("user", "how do we cache embeddings") in texts
    assert ("assistant", "We cache via an on-disk store.") in texts
    # excluded: tool_result-as-user, thinking, queue-operation, tool_use-only
    assert len(chunks) == 2
    assert all("secret reasoning" not in c.text for c in chunks)
    assert all("tool output not human" not in c.text for c in chunks)
    assert all("bash" not in c.text for c in chunks)

def test_offsets_roundtrip_to_source_line():
    chunks = extract_file(FIX, project="proj")
    with open(FIX, "rb") as f:
        data = f.read()
    for c in chunks:
        raw = data[c.byte_offset:c.byte_offset + c.byte_len]
        obj = json.loads(raw)
        assert obj["uuid"] == c.uuid  # offset points at the exact source line

def test_metadata_populated():
    c = next(c for c in extract_file(FIX, project="proj") if c.role == "user")
    assert c.session_id == "sa" and c.project == "proj"
    assert c.git_branch == "main" and c.content_hash


def _write_user_jsonl(tmp_path, *contents):
    p = tmp_path / "s.jsonl"
    lines = [
        json.dumps({"type": "user", "uuid": f"u{i}", "sessionId": "sx", "gitBranch": "main",
                    "message": {"role": "user", "content": content}})
        for i, content in enumerate(contents)
    ]
    p.write_text("\n".join(lines) + "\n")
    return str(p)


def test_drops_pure_harness_boilerplate(tmp_path):
    # a user turn that is ONLY an injected <task-notification> blob is not the user speaking
    path = _write_user_jsonl(tmp_path, "<task-notification>\nbackground task done\n</task-notification>")
    assert extract_file(path, project="p") == []


def test_strips_appended_system_reminder_keeps_real_text(tmp_path):
    # the harness APPENDS a <system-reminder> to a real prompt -> strip the span, keep the prompt
    path = _write_user_jsonl(tmp_path, "Real question about caching.\n\n<system-reminder>do the thing</system-reminder>")
    chunks = extract_file(path, project="p")
    assert len(chunks) == 1
    assert chunks[0].text == "Real question about caching."


def test_keeps_user_quoting_unclosed_tag(tmp_path):
    # a human merely mentioning a tag (no closing tag) must survive untouched
    q = "what does the <system-reminder> tag even mean here?"
    chunks = extract_file(_write_user_jsonl(tmp_path, q), project="p")
    assert len(chunks) == 1 and chunks[0].text == q


def test_drops_caveat_plus_command_echo(tmp_path):
    content = ("Caveat: The messages below were generated by the user while running local "
               "commands. DO NOT respond to these.\n<command-name>/compact</command-name>\n"
               "<command-message>compact</command-message>")
    assert extract_file(_write_user_jsonl(tmp_path, content), project="p") == []


def test_cleaned_chunk_offset_still_points_at_raw_line(tmp_path):
    # text is cleaned, but byte_offset/byte_len must still resolve to the original raw line
    path = _write_user_jsonl(tmp_path, "Keep this.\n<system-reminder>noise</system-reminder>")
    c = extract_file(path, project="p")[0]
    with open(path, "rb") as f:
        raw = f.read()[c.byte_offset:c.byte_offset + c.byte_len]
    assert json.loads(raw)["uuid"] == c.uuid


def test_project_derived_from_cwd_collapses_worktree(tmp_path):
    # project must come from the turn's cwd (worktree -> repo name), NOT the junk
    # folder-derived fallback. Fixes the worktree->hash / self-edu->edu bug.
    p = tmp_path / "s.jsonl"
    p.write_text(json.dumps({
        "type": "user", "uuid": "u1", "sessionId": "sx",
        "cwd": "/Users/me/myrepo/.claude/worktrees/wt-1",
        "message": {"role": "user", "content": "a real question"},
    }) + "\n")
    chunks = extract_file(str(p), project="JUNK-FALLBACK")
    assert chunks and chunks[0].project == "myrepo"


def test_project_falls_back_when_no_cwd(tmp_path):
    # a turn without cwd keeps the passed (folder-derived) project
    path = _write_user_jsonl(tmp_path, "hi there")  # _write_user_jsonl sets no cwd
    chunks = extract_file(path, project="folderproj")
    assert chunks and chunks[0].project == "folderproj"
